### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by IWriteThings**
Issue #2 had some problems. I have expanded on what user MyDigitalLife began and added fixes.

### CODE REVIEW

**Comment by IWriteThings** [comment]
I have left a message at Wowza requesting someone contact me about these changes. I would like to get this tested/blessed by the Wowza devs and pushed through as soon as possible. A lot of us really need this.

**Comment by IWriteThings** [comment]
I have left messages with Wowza, contacted our rep, and also tried to reach out through another company that does high traffic in Wowza resales. No news yet. Still trying folks.

**Comment by mcrayshill** [comment]
Hello IWriteThings,

I apologize for the latency in response. I have sent a direct message to the repository owner to follow up with you later today when they are on shift. 

If you still experience any lack of response within the next 24 hours, please send an email to support@wowza.com and be sure to include "_Attention: Mac > Regarding GitHub_" in the body of the message along with your contact information so I am able to follow up with you properly. 

Again, please accept our apologies. 

Regards,
Mac Hill
Team Lead, Support Services

**Comment by IWriteThings** [comment]
@mcrayshill 

Sir, I have sent you over an email with thee body of the message as per your request. I included my contact information and a brief explanation of what we are trying to fix with these changes. Thanks a bunch for taking the time to reach out.

**Comment by rogerlittin** [comment]
Hi,

I've managed to merge the pull request manually. It was difficult because there were a lot of renamed and moved files that had subsequently been modified. Please check to make sure it is correct.

-Roger.

**Pull request closed without merging**
