### PR TITLE
Added composer support

### PR DESCRIPTION
**Pull request by MyDigitalLife**
I've made a few few changes to make the project more compatible with composer:

- Added composer.json file.
- Renamed files for composer autoloader.
- Moved the settings to a settings class.
- Move the preparePropertiesForRequest to the Wowza class so there is less duplicate code.
- Changed properties used by preparePropertiesForRequest to protected to make sure the function works from the Wowza class.

I also updated the autoloader file included and it should still work (did not test is). Also the included tests are not really how i would do it. Using phpunit is a lot better and done by almost every modern PHP project.

You should also add a minimal phpversion in the composer file. I mostly work with PHP 7 and write my array with short syntax so some changes made it php 5.4 and up.

### CODE REVIEW

**Comment by IWriteThings** [comment]
Can we get this added for composer support? It would make inclusion in my project easier.

**Comment by pascalbaljet** [comment]
Same here, this would be awesome!

**Comment by seisvalt** [comment]
Same here

**Comment by cbevans** [comment]
+1 - please!

**Comment by MyDigitalLife** [comment]
Hi @dnelsonwowz and @myoung1620. It looks like you guys are the maintainers of this repo. Is there any chance this will be merged or at least discussed?

**Comment by paulm17** [comment]
Would like to see composer support added as well!

**Comment by caiblack** [comment]
Composer support would be super-useful.

**Comment by zalaudekr** [comment]
Composer support +1 vote

**Comment by IWriteThings** [comment]
I am rewriting this as necessary. Will have composer support soon.

**Comment by IWriteThings** [comment]
I am almost done fixing the conflicts and resolving issues. I am going to fix the autoloader to be more compliant and then we should be good to go.

**Comment by IWriteThings** [comment]
Please see issue #16 . I will call Wowza support today and see if I can speak to them about these changes.

**Comment by rogerlittin** [comment]
Hi,

Pull request had to be merged manually because there were a lot of renamed & moved files that had subsequently been changed. Please check it to make sure it is correct.

-Roger.

**Pull request closed without merging**
